name: haarlem-festival

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      APP_URL: ${APP_URL:-http://localhost}
      APP_ENV: ${APP_ENV:-local}
      MAIL_HOST: ${MAIL_HOST:-}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-noreply@haarlemfestival.nl}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Haarlem Festival}
      MAIL_FORCE_SEND: ${MAIL_FORCE_SEND:-false}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      MAIL_DEBUG: ${MAIL_DEBUG:-false}

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql

volumes:
  mysqldata: { }
