-- Fix for migration-v26: correct column name UpdatedAtUtc → omitted (uses default)
-- Inserts CmsItem records for storytelling-detail page (CmsPageId=7)

INSERT INTO `CmsItem` (`CmsItemId`, `CmsSectionId`, `ItemKey`, `ItemType`, `TextValue`, `HtmlValue`, `MediaAssetId`) VALUES
(409,62,'about_heading','HEADING','Omdenken Podcast',NULL,NULL),
(410,62,'about_body','HTML',NULL,'<p>A live podcast recording with audience participation. Thought-provoking conversations that challenge conventional thinking and inspire new perspectives.</p>',NULL),
(411,62,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(412,62,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(413,62,'highlight_1_title','TEXT','Live Recording',NULL,NULL),
(414,62,'highlight_1_description','TEXT','Be part of a live podcast recording in front of an audience.',NULL,NULL),
(415,62,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(416,62,'highlight_2_title','TEXT','Audience Participation',NULL,NULL),
(417,62,'highlight_2_description','TEXT','Your questions and insights shape the conversation.',NULL,NULL),
(418,62,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(419,62,'highlight_3_title','TEXT','New Perspectives',NULL,NULL),
(420,62,'highlight_3_description','TEXT','Discover how reframing challenges can lead to creative solutions.',NULL,NULL),
(421,62,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(422,62,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(423,62,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(424,62,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(425,62,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(426,62,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(427,62,'video_url','TEXT','',NULL,NULL),
(428,63,'about_heading','HEADING','About Buurderij Haarlem',NULL,NULL),
(429,63,'about_body','HTML',NULL,'<p>Buurderij Haarlem is a local food community where neighbours order directly from farmers and small producers in the region. What started as a simple idea grew into a place where food is not just bought, but shared as a story.</p><p>During this storytelling session, the audience is taken behind the scenes of Buurderij Haarlem. The story explains how local entrepreneurs, volunteers, and residents work together to create a system based on trust, transparency, and respect for nature.</p>',NULL),
(430,63,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(431,63,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(432,63,'highlight_1_title','TEXT','From Farmer to Neighbour',NULL,NULL),
(433,63,'highlight_1_description','TEXT','A personal story about how local farmers connect directly with Haarlem residents, focusing on trust, fair pricing, and the journey food takes from land to table.',NULL,NULL),
(434,63,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(435,63,'highlight_2_title','TEXT','Building a Local Food Community',NULL,NULL),
(436,63,'highlight_2_description','TEXT','How Buurderij Haarlem became more than a marketplace - weekly meetups created friendships and a shared sense of responsibility for local food.',NULL,NULL),
(437,63,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(438,63,'highlight_3_title','TEXT','Food with a Future',NULL,NULL),
(439,63,'highlight_3_description','TEXT','How Buurderij Haarlem supports seasonal food, reduces waste, and encourages conscious consumption for future generations.',NULL,NULL),
(440,63,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(441,63,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(442,63,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(443,63,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/where-stories-come-alive.jpg',NULL,NULL),
(444,63,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(445,63,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(446,63,'video_url','TEXT','',NULL,NULL),
(447,64,'about_heading','HEADING','Corrie voor kinderen',NULL,NULL),
(448,64,'about_body','HTML',NULL,'<p>A family storytelling experience that brings the story of Corrie to life for young audiences with engaging performances and vivid imagery.</p>',NULL),
(449,64,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(450,64,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(451,64,'highlight_1_title','TEXT','Stories for Every Child',NULL,NULL),
(452,64,'highlight_1_description','TEXT','An accessible and joyful storytelling session designed with children in mind.',NULL,NULL),
(453,64,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(454,64,'highlight_2_title','TEXT','Imagination in Action',NULL,NULL),
(455,64,'highlight_2_description','TEXT','Watch as the performer brings characters to life through voice, gesture, and storytelling.',NULL,NULL),
(456,64,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(457,64,'highlight_3_title','TEXT','A Shared Experience',NULL,NULL),
(458,64,'highlight_3_description','TEXT','A session that brings families and communities together around shared stories.',NULL,NULL),
(459,64,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(460,64,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(461,64,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(462,64,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(463,64,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(464,64,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(465,64,'video_url','TEXT','',NULL,NULL),
(466,65,'about_heading','HEADING','Winnaars verhalenvertel wedstrijd',NULL,NULL),
(467,65,'about_body','HTML',NULL,'<p>The winners of this year verhalenvertel competition share their winning stories about Haarlem, its people, and its spirit.</p>',NULL),
(468,65,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(469,65,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(470,65,'highlight_1_title','TEXT','Competition Winners',NULL,NULL),
(471,65,'highlight_1_description','TEXT','Hear from the storytellers who won the Haarlem storytelling competition.',NULL,NULL),
(472,65,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(473,65,'highlight_2_title','TEXT','Stories About Haarlem',NULL,NULL),
(474,65,'highlight_2_description','TEXT','Each winner tells a story rooted in the city culture and everyday life.',NULL,NULL),
(475,65,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(476,65,'highlight_3_title','TEXT','Community Voice',NULL,NULL),
(477,65,'highlight_3_description','TEXT','The competition celebrates storytelling as a way to strengthen community bonds.',NULL,NULL),
(478,65,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(479,65,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(480,65,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(481,65,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(482,65,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(483,65,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(484,65,'video_url','TEXT','',NULL,NULL),
(485,66,'about_heading','HEADING','Het verhaal van de Oeserzwammerij',NULL,NULL),
(486,66,'about_body','HTML',NULL,'<p>An intimate storytelling session about the Oeserzwammerij, a local initiative growing oyster mushrooms sustainably in Haarlem.</p>',NULL),
(487,66,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(488,66,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(489,66,'highlight_1_title','TEXT','Sustainable Innovation',NULL,NULL),
(490,66,'highlight_1_description','TEXT','Learn how local entrepreneurs are growing food sustainably in the city.',NULL,NULL),
(491,66,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(492,66,'highlight_2_title','TEXT','Community Impact',NULL,NULL),
(493,66,'highlight_2_description','TEXT','The Oeserzwammerij connects growers, volunteers, and consumers.',NULL,NULL),
(494,66,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(495,66,'highlight_3_title','TEXT','From Waste to Food',NULL,NULL),
(496,66,'highlight_3_description','TEXT','Using coffee grounds and organic waste to grow nutritious mushrooms.',NULL,NULL),
(497,66,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(498,66,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(499,66,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(500,66,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(501,66,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(502,66,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(503,66,'video_url','TEXT','',NULL,NULL),
(504,67,'about_heading','HEADING','Flip Thinking Podcast',NULL,NULL),
(505,67,'about_body','HTML',NULL,'<p>A live recording of the popular Flip Thinking podcast, where hosts and guests explore the art of reframing problems into opportunities.</p>',NULL),
(506,67,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(507,67,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(508,67,'highlight_1_title','TEXT','Reframe Your World',NULL,NULL),
(509,67,'highlight_1_description','TEXT','Learn practical techniques for turning obstacles into opportunities.',NULL,NULL),
(510,67,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(511,67,'highlight_2_title','TEXT','Live Podcast Recording',NULL,NULL),
(512,67,'highlight_2_description','TEXT','Experience the magic of a podcast recorded before a live audience.',NULL,NULL),
(513,67,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(514,67,'highlight_3_title','TEXT','Q and A with Audience',NULL,NULL),
(515,67,'highlight_3_description','TEXT','After the recording, guests take questions from the audience.',NULL,NULL),
(516,67,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(517,67,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(518,67,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(519,67,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(520,67,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(521,67,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(522,67,'video_url','TEXT','',NULL,NULL),
(523,68,'about_heading','HEADING','Meneer Anansi',NULL,NULL),
(524,68,'about_body','HTML',NULL,'<p>Meneer Anansi brings the West African trickster spider to life in Dutch, weaving together folklore, humour, and wisdom in a totally original way.</p>',NULL),
(525,68,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(526,68,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/anansi-conversation.jpg',NULL,NULL),
(527,68,'highlight_1_title','TEXT','Anansi the Trickster',NULL,NULL),
(528,68,'highlight_1_description','TEXT','The beloved spider of West African folklore comes alive on stage.',NULL,NULL),
(529,68,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(530,68,'highlight_2_title','TEXT','Dutch Folk and World Heritage',NULL,NULL),
(531,68,'highlight_2_description','TEXT','Ancient Anansi stories told in Dutch, bridging cultures and generations.',NULL,NULL),
(532,68,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/anansi-conversation.jpg',NULL,NULL),
(533,68,'highlight_3_title','TEXT','Humour and Wisdom',NULL,NULL),
(534,68,'highlight_3_description','TEXT','Each Anansi story carries a lesson wrapped in laughter and surprise.',NULL,NULL),
(535,68,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/anansi-drip.jpg',NULL,NULL),
(536,68,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(537,68,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/anansi-conversation.jpg',NULL,NULL),
(538,68,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/anansi-drip.jpg',NULL,NULL),
(539,68,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/anansi-visser.jpg',NULL,NULL),
(540,68,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(541,68,'video_url','TEXT','',NULL,NULL),
(542,69,'about_heading','HEADING','Mister Anansi',NULL,NULL),
(543,69,'about_body','HTML',NULL,'<p>Mister Anansi is the English-language version of the beloved spider trickster story, perfect for international visitors and English-speaking families.</p>',NULL),
(544,69,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(545,69,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/anansi-visser.jpg',NULL,NULL),
(546,69,'highlight_1_title','TEXT','In English',NULL,NULL),
(547,69,'highlight_1_description','TEXT','The Anansi story performed in English for international audiences.',NULL,NULL),
(548,69,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(549,69,'highlight_2_title','TEXT','Universal Themes',NULL,NULL),
(550,69,'highlight_2_description','TEXT','Stories of cunning, community, and creativity that transcend cultures.',NULL,NULL),
(551,69,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/anansi-conversation.jpg',NULL,NULL),
(552,69,'highlight_3_title','TEXT','World Folklore on Stage',NULL,NULL),
(553,69,'highlight_3_description','TEXT','Experience the rich tradition of West African oral storytelling at Haarlem Festival.',NULL,NULL),
(554,69,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/anansi-drip.jpg',NULL,NULL),
(555,69,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/anansi-pointing.png',NULL,NULL),
(556,69,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/anansi-visser.jpg',NULL,NULL),
(557,69,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/anansi-conversation.jpg',NULL,NULL),
(558,69,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/anansi-drip.jpg',NULL,NULL),
(559,69,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(560,69,'video_url','TEXT','',NULL,NULL),
(561,70,'about_heading','HEADING','Podcastlast Haarlem Special',NULL,NULL),
(562,70,'about_body','HTML',NULL,'<p>A special live edition of the Podcastlast podcast, recorded at the Haarlem Festival with candid conversations and local insights.</p>',NULL),
(563,70,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(564,70,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(565,70,'highlight_1_title','TEXT','Haarlem Special Edition',NULL,NULL),
(566,70,'highlight_1_description','TEXT','A one-of-a-kind live episode recorded exclusively at the festival.',NULL,NULL),
(567,70,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(568,70,'highlight_2_title','TEXT','Local Conversations',NULL,NULL),
(569,70,'highlight_2_description','TEXT','Featuring guests from Haarlem creative and cultural scene.',NULL,NULL),
(570,70,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(571,70,'highlight_3_title','TEXT','Live Audience Experience',NULL,NULL),
(572,70,'highlight_3_description','TEXT','Be part of the recording and feel the energy of a live podcast taping.',NULL,NULL),
(573,70,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(574,70,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(575,70,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(576,70,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(577,70,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(578,70,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(579,70,'video_url','TEXT','',NULL,NULL),
(580,71,'about_heading','HEADING','De geschiedenis van familie ten Boom',NULL,NULL),
(581,71,'about_body','HTML',NULL,'<p>The remarkable story of the ten Boom family, whose Haarlem home became a refuge during World War II, sheltering Jewish families at great personal risk.</p>',NULL),
(582,71,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(583,71,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(584,71,'highlight_1_title','TEXT','A Story of Courage',NULL,NULL),
(585,71,'highlight_1_description','TEXT','The ten Boom family risked everything to shelter Jews during the occupation.',NULL,NULL),
(586,71,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(587,71,'highlight_2_title','TEXT','Haarlem in History',NULL,NULL),
(588,71,'highlight_2_description','TEXT','Explore how one family home became a symbol of resistance and compassion.',NULL,NULL),
(589,71,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(590,71,'highlight_3_title','TEXT','Legacy and Memory',NULL,NULL),
(591,71,'highlight_3_description','TEXT','Their story lives on as an inspiration for future generations.',NULL,NULL),
(592,71,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(593,71,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(594,71,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(595,71,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(596,71,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(597,71,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(598,71,'video_url','TEXT','',NULL,NULL),
(599,72,'about_heading','HEADING','The History of the Ten Boom Family',NULL,NULL),
(600,72,'about_body','HTML',NULL,'<p>The story of the ten Boom family told in English. During WWII they used their Haarlem shop to hide Jewish families, leaving a lasting legacy on the city.</p>',NULL),
(601,72,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(602,72,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(603,72,'highlight_1_title','TEXT','In English',NULL,NULL),
(604,72,'highlight_1_description','TEXT','The ten Boom family story told for international visitors.',NULL,NULL),
(605,72,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(606,72,'highlight_2_title','TEXT','Wartime Haarlem',NULL,NULL),
(607,72,'highlight_2_description','TEXT','Step back in time to a Haarlem that faced unimaginable choices.',NULL,NULL),
(608,72,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(609,72,'highlight_3_title','TEXT','Hope and Resilience',NULL,NULL),
(610,72,'highlight_3_description','TEXT','A story about human courage that resonates across generations and borders.',NULL,NULL),
(611,72,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(612,72,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(613,72,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/picture-looking-text.jpg',NULL,NULL),
(614,72,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(615,72,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(616,72,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(617,72,'video_url','TEXT','',NULL,NULL),
(618,73,'about_heading','HEADING','Winners of the Storytelling Competition',NULL,NULL),
(619,73,'about_body','HTML',NULL,'<p>The best storytellers from this year competition take the stage to share their winning tales about Haarlem in English, selected for creativity, emotional depth, and unique perspective.</p>',NULL),
(620,73,'about_image_1','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(621,73,'about_image_2','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(622,73,'highlight_1_title','TEXT','Competition Winners',NULL,NULL),
(623,73,'highlight_1_description','TEXT','The English-language winners of the storytelling competition share their best work.',NULL,NULL),
(624,73,'highlight_1_image','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(625,73,'highlight_2_title','TEXT','Stories About Haarlem',NULL,NULL),
(626,73,'highlight_2_description','TEXT','Each story is rooted in the life and character of the city.',NULL,NULL),
(627,73,'highlight_2_image','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(628,73,'highlight_3_title','TEXT','New Voices',NULL,NULL),
(629,73,'highlight_3_description','TEXT','Discover emerging storytelling talent from Haarlem and beyond.',NULL,NULL),
(630,73,'highlight_3_image','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(631,73,'gallery_image_1','IMAGE_PATH','/assets/Image/storytelling/d-student.jpg',NULL,NULL),
(632,73,'gallery_image_2','IMAGE_PATH','/assets/Image/storytelling/d-student2.jpg',NULL,NULL),
(633,73,'gallery_image_3','IMAGE_PATH','/assets/Image/storytelling/m-student.jpg',NULL,NULL),
(634,73,'gallery_image_4','IMAGE_PATH','/assets/Image/storytelling/building.jpg',NULL,NULL),
(635,73,'gallery_image_5','IMAGE_PATH','/assets/Image/storytelling/entrance-kweek.jpg',NULL,NULL),
(636,73,'video_url','TEXT','',NULL,NULL);

ALTER TABLE `CmsItem` AUTO_INCREMENT = 637;
