<?php

declare(strict_types=1);

namespace App\Tickets;

use App\DTOs\Tickets\QrCodeMatrix;
use App\Exceptions\TicketQrCodeException;
use App\Tickets\Interfaces\IQrCodeGenerator;

/**
 * Minimal QR generator for short ASCII ticket codes.
 *
 * Uses QR version 2-L in byte mode with mask pattern 0, which is enough for the
 * compact ticket codes generated by TicketCodeGenerator.
 */
final class QrCodeGenerator implements IQrCodeGenerator
{
    private const VERSION = 2;
    private const SIZE = 25;
    private const DATA_CODEWORDS = 34;
    private const EC_CODEWORDS = 10;

    public function generate(string $payload): QrCodeMatrix
    {
        $data = $this->readPayloadBytes($payload);
        $dataCodewords = $this->buildDataCodewords($data);
        $allCodewords = array_merge($dataCodewords, $this->buildErrorCorrectionCodewords($dataCodewords));
        $bits = $this->toBitStream($allCodewords);

        $modules = array_fill(0, self::SIZE, array_fill(0, self::SIZE, false));
        $reserved = array_fill(0, self::SIZE, array_fill(0, self::SIZE, false));
        $dataModules = array_fill(0, self::SIZE, array_fill(0, self::SIZE, false));

        $this->drawFunctionPatterns($modules, $reserved);
        $this->placeDataBits($modules, $reserved, $dataModules, $bits);
        $this->applyMaskPattern0($modules, $dataModules);
        $this->drawFormatBits($modules);

        return new QrCodeMatrix(size: self::SIZE, modules: $modules);
    }

    /**
     * @return int[]
     */
    private function readPayloadBytes(string $payload): array
    {
        if ($payload === '') {
            throw new TicketQrCodeException('Ticket QR payload cannot be empty.');
        }

        if (!mb_check_encoding($payload, 'ASCII')) {
            throw new TicketQrCodeException('Ticket QR payload must be ASCII.');
        }

        $bytes = array_values(unpack('C*', $payload) ?: []);
        if (count($bytes) > 32) {
            throw new TicketQrCodeException('Ticket QR payload is too long for the fixed QR version.');
        }

        return $bytes;
    }

    /**
     * @param int[] $bytes
     * @return int[]
     */
    private function buildDataCodewords(array $bytes): array
    {
        $bits = [];
        $this->appendBits($bits, 0b0100, 4);
        $this->appendBits($bits, count($bytes), 8);

        foreach ($bytes as $byte) {
            $this->appendBits($bits, $byte, 8);
        }

        $capacity = self::DATA_CODEWORDS * 8;
        $remaining = $capacity - count($bits);
        $this->appendBits($bits, 0, min(4, $remaining));

        while (count($bits) % 8 !== 0) {
            $bits[] = 0;
        }

        $codewords = [];
        foreach (array_chunk($bits, 8) as $chunk) {
            $codewords[] = $this->bitsToByte($chunk);
        }

        $padBytes = [0xEC, 0x11];
        for ($i = count($codewords); $i < self::DATA_CODEWORDS; $i++) {
            $codewords[] = $padBytes[$i % 2];
        }

        return $codewords;
    }

    /**
     * @param int[] $dataCodewords
     * @return int[]
     */
    private function buildErrorCorrectionCodewords(array $dataCodewords): array
    {
        [$exp, $log] = $this->buildGaloisTables();
        $generator = $this->buildGeneratorPolynomial(self::EC_CODEWORDS, $exp, $log);
        $message = array_merge($dataCodewords, array_fill(0, self::EC_CODEWORDS, 0));

        foreach ($dataCodewords as $index => $coefficient) {
            if ($coefficient === 0) {
                continue;
            }

            foreach ($generator as $offset => $value) {
                $message[$index + $offset] ^= $this->gfMultiply($value, $coefficient, $exp, $log);
            }
        }

        return array_slice($message, -self::EC_CODEWORDS);
    }

    /**
     * @return array{0: int[], 1: int[]}
     */
    private function buildGaloisTables(): array
    {
        $exp = array_fill(0, 512, 0);
        $log = array_fill(0, 256, 0);
        $value = 1;

        for ($i = 0; $i < 255; $i++) {
            $exp[$i] = $value;
            $log[$value] = $i;
            $value <<= 1;

            if (($value & 0x100) !== 0) {
                $value ^= 0x11D;
            }
        }

        for ($i = 255; $i < 512; $i++) {
            $exp[$i] = $exp[$i - 255];
        }

        return [$exp, $log];
    }

    /**
     * @param int[] $exp
     * @param int[] $log
     * @return int[]
     */
    private function buildGeneratorPolynomial(int $degree, array $exp, array $log): array
    {
        $polynomial = [1];

        for ($i = 0; $i < $degree; $i++) {
            $polynomial = $this->multiplyPolynomials($polynomial, [1, $exp[$i]], $exp, $log);
        }

        return $polynomial;
    }

    /**
     * @param int[] $left
     * @param int[] $right
     * @param int[] $exp
     * @param int[] $log
     * @return int[]
     */
    private function multiplyPolynomials(array $left, array $right, array $exp, array $log): array
    {
        $result = array_fill(0, count($left) + count($right) - 1, 0);

        foreach ($left as $leftIndex => $leftValue) {
            foreach ($right as $rightIndex => $rightValue) {
                $result[$leftIndex + $rightIndex] ^= $this->gfMultiply($leftValue, $rightValue, $exp, $log);
            }
        }

        return $result;
    }

    /**
     * @param int[] $exp
     * @param int[] $log
     */
    private function gfMultiply(int $left, int $right, array $exp, array $log): int
    {
        if ($left === 0 || $right === 0) {
            return 0;
        }

        return $exp[$log[$left] + $log[$right]];
    }

    /**
     * @param int[] $codewords
     * @return int[]
     */
    private function toBitStream(array $codewords): array
    {
        $bits = [];

        foreach ($codewords as $codeword) {
            $this->appendBits($bits, $codeword, 8);
        }

        return $bits;
    }

    /**
     * @param int[] $bits
     */
    private function appendBits(array &$bits, int $value, int $bitCount): void
    {
        for ($shift = $bitCount - 1; $shift >= 0; $shift--) {
            $bits[] = ($value >> $shift) & 1;
        }
    }

    /**
     * @param int[] $bits
     */
    private function bitsToByte(array $bits): int
    {
        $value = 0;

        foreach ($bits as $bit) {
            $value = ($value << 1) | $bit;
        }

        return $value;
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     */
    private function drawFunctionPatterns(array &$modules, array &$reserved): void
    {
        $this->drawFinderPattern($modules, $reserved, 0, 0);
        $this->drawFinderPattern($modules, $reserved, self::SIZE - 7, 0);
        $this->drawFinderPattern($modules, $reserved, 0, self::SIZE - 7);
        $this->drawAlignmentPattern($modules, $reserved, 18, 18);
        $this->drawTimingPatterns($modules, $reserved);
        $this->reserveFormatAreas($modules, $reserved);
        $modules[4 * self::VERSION + 9][8] = true;
        $reserved[4 * self::VERSION + 9][8] = true;
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     */
    private function drawFinderPattern(array &$modules, array &$reserved, int $startX, int $startY): void
    {
        for ($dy = -1; $dy <= 7; $dy++) {
            for ($dx = -1; $dx <= 7; $dx++) {
                $x = $startX + $dx;
                $y = $startY + $dy;

                if ($x < 0 || $x >= self::SIZE || $y < 0 || $y >= self::SIZE) {
                    continue;
                }

                $inside = $dx >= 0 && $dx <= 6 && $dy >= 0 && $dy <= 6;
                $dark = $inside && (
                    $dx === 0 || $dx === 6 || $dy === 0 || $dy === 6
                    || ($dx >= 2 && $dx <= 4 && $dy >= 2 && $dy <= 4)
                );

                $modules[$y][$x] = $dark;
                $reserved[$y][$x] = true;
            }
        }
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     */
    private function drawAlignmentPattern(array &$modules, array &$reserved, int $centerX, int $centerY): void
    {
        for ($dy = -2; $dy <= 2; $dy++) {
            for ($dx = -2; $dx <= 2; $dx++) {
                $x = $centerX + $dx;
                $y = $centerY + $dy;
                $modules[$y][$x] = max(abs($dx), abs($dy)) !== 1;
                $reserved[$y][$x] = true;
            }
        }
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     */
    private function drawTimingPatterns(array &$modules, array &$reserved): void
    {
        for ($index = 8; $index < self::SIZE - 8; $index++) {
            $dark = $index % 2 === 0;
            $modules[6][$index] = $dark;
            $modules[$index][6] = $dark;
            $reserved[6][$index] = true;
            $reserved[$index][6] = true;
        }
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     */
    private function reserveFormatAreas(array &$modules, array &$reserved): void
    {
        for ($index = 0; $index < 9; $index++) {
            if ($index !== 6) {
                $modules[8][$index] = false;
                $modules[$index][8] = false;
                $reserved[8][$index] = true;
                $reserved[$index][8] = true;
            }
        }

        for ($index = self::SIZE - 8; $index < self::SIZE; $index++) {
            $modules[8][$index] = false;
            $modules[$index][8] = false;
            $reserved[8][$index] = true;
            $reserved[$index][8] = true;
        }
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $reserved
     * @param bool[][] $dataModules
     * @param int[] $bits
     */
    private function placeDataBits(array &$modules, array $reserved, array &$dataModules, array $bits): void
    {
        $bitIndex = 0;
        $movingUp = true;

        for ($right = self::SIZE - 1; $right >= 1; $right -= 2) {
            if ($right === 6) {
                $right--;
            }

            for ($offset = 0; $offset < self::SIZE; $offset++) {
                $y = $movingUp ? self::SIZE - 1 - $offset : $offset;

                for ($columnOffset = 0; $columnOffset < 2; $columnOffset++) {
                    $x = $right - $columnOffset;
                    if ($reserved[$y][$x]) {
                        continue;
                    }

                    if ($bitIndex < count($bits)) {
                        $modules[$y][$x] = $bits[$bitIndex] === 1;
                        $dataModules[$y][$x] = true;
                        $bitIndex++;
                        continue;
                    }

                    $modules[$y][$x] = false;
                }
            }

            $movingUp = !$movingUp;
        }
    }

    /**
     * @param bool[][] $modules
     * @param bool[][] $dataModules
     */
    private function applyMaskPattern0(array &$modules, array $dataModules): void
    {
        for ($y = 0; $y < self::SIZE; $y++) {
            for ($x = 0; $x < self::SIZE; $x++) {
                if (!$dataModules[$y][$x]) {
                    continue;
                }

                if ((($x + $y) % 2) === 0) {
                    $modules[$y][$x] = !$modules[$y][$x];
                }
            }
        }
    }

    /**
     * @param bool[][] $modules
     */
    private function drawFormatBits(array &$modules): void
    {
        $bits = $this->buildFormatBits();

        for ($i = 0; $i <= 5; $i++) {
            $modules[8][$i] = $this->getBit($bits, $i);
        }

        $modules[8][7] = $this->getBit($bits, 6);
        $modules[8][8] = $this->getBit($bits, 7);
        $modules[7][8] = $this->getBit($bits, 8);

        for ($i = 9; $i <= 14; $i++) {
            $modules[14 - $i][8] = $this->getBit($bits, $i);
        }

        for ($i = 0; $i <= 7; $i++) {
            $modules[self::SIZE - 1 - $i][8] = $this->getBit($bits, $i);
        }

        for ($i = 8; $i <= 14; $i++) {
            $modules[8][self::SIZE - 15 + $i] = $this->getBit($bits, $i);
        }

        $modules[self::SIZE - 8][8] = true;
    }

    private function buildFormatBits(): int
    {
        $formatData = (0b01 << 3);
        $remainder = $formatData << 10;

        for ($bit = 14; $bit >= 10; $bit--) {
            if ((($remainder >> $bit) & 1) !== 0) {
                $remainder ^= 0x537 << ($bit - 10);
            }
        }

        return (($formatData << 10) | $remainder) ^ 0x5412;
    }

    private function getBit(int $value, int $index): bool
    {
        return (($value >> $index) & 1) !== 0;
    }
}
